# Generated by Django 5.2.17 on 2026-09-24 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.internet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('link_type', models.CharField(choices=[('fibra_optica', 'Fibra óptica'), ('radioenlace', 'Radioenlace'), ('cobre', 'Cobre'), ('satelite', 'Satélite'), ('otro', 'Otro')], max_length=40)),
                ('contracted_speed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('speed_unit', models.CharField(default='Mbps', max_length=20)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('circuit_id', models.CharField(blank=True, default='', max_length=120)),
                ('connection_medium', models.CharField(blank=True, default='', max_length=120)),
                ('technical_observations', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('observations', models.TextField(blank=True, default='', max_length=500)),
                ('marked_with_observations', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_services_created', to=settings.AUTH_USER_MODEL)),
                ('ods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='catalogs.ods')),
                ('oes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='catalogs.oes')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='catalogs.provider')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='catalogs.responsible')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='catalogs.site')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_services_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio de Internet',
                'verbose_name_plural': 'Servicios de Internet',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='InternetServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='internet.internetservice')),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Vigente'), ('expired', 'Vencido'), ('inactive', 'Inactivo')], default='active', max_length=20)),
                ('observations', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_contracts_created', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogs.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='internet.internetservice')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_contracts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='ServiceDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Presentado'), ('observed', 'Observado'), ('remedied', 'Subsanado'), ('approved', 'Aprobado'), ('late', 'Fuera de plazo')], default='pending', max_length=20)),
                ('observations', models.TextField(blank=True, default='')),
                ('submitted_on_time', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='internet.servicecontract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_deliverables_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='internet.internetservice')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_deliverables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-due_date',),
            },
        ),
        migrations.CreateModel(
            name='ServiceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('cause', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField(blank=True, default='')),
                ('attribution', models.CharField(blank=True, default='', max_length=255)),
                ('downtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_incidents_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internet_incidents', to='catalogs.responsible')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='internet.internetservice')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_incidents_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('related_type', models.CharField(choices=[('service', 'Servicio'), ('contract', 'Contrato'), ('deliverable', 'Entregable'), ('incident', 'Incidencia')], max_length=20)),
                ('document_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=apps.internet.models.private_document_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='internet.servicecontract')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='internet.servicedeliverable')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_documents', to='catalogs.documenttype')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='internet.internetservice')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='internet.serviceincident')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='internetservice',
            index=models.Index(fields=['code'], name='internet_in_code_36a0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='internetservice',
            index=models.Index(fields=['end_date'], name='internet_in_end_dat_109eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='internetservice',
            index=models.Index(fields=['is_active', 'end_date'], name='internet_in_is_acti_7bd773_idx'),
        ),
        migrations.AddIndex(
            model_name='internetservice',
            index=models.Index(fields=['site'], name='internet_in_site_id_8aa53b_idx'),
        ),
        migrations.AddIndex(
            model_name='internetservice',
            index=models.Index(fields=['provider'], name='internet_in_provide_c85ee2_idx'),
        ),
        migrations.AddConstraint(
            model_name='internetservice',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='internet_service_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='internetservice',
            constraint=models.CheckConstraint(condition=models.Q(('contracted_speed__gt', 0)), name='internet_service_speed_positive'),
        ),
        migrations.AddConstraint(
            model_name='internetservice',
            constraint=models.CheckConstraint(condition=models.Q(('ods__isnull', False), ('oes__isnull', False), _connector='OR'), name='internet_service_ods_or_oes_required'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['contract_number'], name='internet_se_contrac_e565c3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['service', 'is_active'], name='internet_se_service_fa92be_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecontract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='internet_contract_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='servicedeliverable',
            index=models.Index(fields=['service', 'status'], name='internet_se_service_5ee991_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceincident',
            index=models.Index(fields=['ticket_code'], name='internet_se_ticket__a9da8a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceincident',
            index=models.Index(fields=['service', 'status'], name='internet_se_service_10d1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedocument',
            index=models.Index(fields=['related_type', 'uploaded_at'], name='internet_se_related_9c78a4_idx'),
        ),
    ]
